name: Build app
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: ["v*"]
  pull_request:
    branches: [ "master" ]
jobs:
  build-executable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_prefix: lin
            pyinstaller_options:
          - os: windows-latest
            artifact_prefix: win
            pyinstaller_options: --hide-console hide-late

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7.0.1
      - name: Install uv
        # https://github.com/astral-sh/setup-uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.7"
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --locked --all-extras
      - name: Export app version
        shell: bash
        run: echo "VERSION=$(uv run cbx_converter --version)" >> $GITHUB_ENV
      - name: Generate standalone app
        run: >
          uv run pyinstaller exe.py
          --name cbx-converter-${{ env.VERSION }}
          --onefile
          --clean
          ${{ matrix.pyinstaller_options }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cbx-converter-${{ env.VERSION }}-${{ matrix.artifact_prefix }}-${{ github.run_id }}
          path: dist/cbx-converter-*
